name       : sdl2
version    : 2.0.3
release    : 3
source     :
    - https://www.libsdl.org/release/SDL2-2.0.3.tar.gz : a5a69a6abf80bcce713fa873607735fe712f44276a7f048d60a61bb2f6b3c90c
license    :
    - zlib
summary    : Simple DirectMedia Layer
builddeps  :
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig(wayland-client)
    - pkgconfig32(wayland-client)
    - pkgconfig(libpulse)
    - pkgconfig32(libpulse)
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xinerama)
    - pkgconfig32(xinerama)
    - pkgconfig(xcursor)
    - pkgconfig32(xcursor)
    - pkgconfig(xscrnsaver)
    - pkgconfig32(xscrnsaver)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
patterns   :
    - devel : /usr/bin
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
setup      : |
    %configure --prefix=/usr \
               --enable-shared \
               --with-x \
               --enable-alsa \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath
build      : |
    %make
install    : |
    %make_install
