name       : sdl2
version    : 2.0.6
release    : 10
source     :
    - https://www.libsdl.org/release/SDL2-2.0.6.tar.gz : 03658b5660d16d7b31263a691e058ed37acdab155d68dabbad79998fb552c5df
license    : Zlib
component  : multimedia.library
summary    : Simple DirectMedia Layer
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig(wayland-client)
    - pkgconfig32(wayland-client)
    - pkgconfig(libpulse)
    - pkgconfig32(libpulse)
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(ice)
    - pkgconfig32(ice)
    - pkgconfig(xinerama)
    - pkgconfig32(xinerama)
    - pkgconfig(xcursor)
    - pkgconfig32(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig32(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig32(xscrnsaver)
    - pkgconfig(wayland-client)
    - pkgconfig32(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig32(wayland-protocols)
    - pkgconfig(xkbcommon)
    - pkgconfig32(xkbcommon)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
patterns   :
    - devel : /usr/bin
setup      : |
    %configure --prefix=/usr \
               --enable-shared \
               --with-x \
               --enable-alsa \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath \
               --enable-video-wayland \
               --enable-video-x11 \
               --enable-sdl-dlopen \
build      : |
    %make
install    : |
    %make_install
