name       : sdl2
version    : 2.0.8
release    : 15
source     :
    - https://www.libsdl.org/release/SDL2-2.0.8.tar.gz : edc77c57308661d576e843344d8638e025a7818bff73f8fbfab09c3c5fd092ec
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : Simple DirectMedia Layer
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(ice)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(wayland-client)
    - pkgconfig32(wayland-protocols)
    - pkgconfig32(x11)
    - pkgconfig32(xcursor)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xscrnsaver)
    - sndio-32bit-devel
patterns   :
    - devel : /usr/bin
setup      : |
    %patch -p1 < $pkgfiles/Fix-gamepads.patch
    %configure --prefix=/usr \
               --enable-shared \
               --with-x \
               --enable-alsa \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath \
               --enable-video-wayland \
               --enable-video-x11 \
               --enable-sdl-dlopen \
               --disable-rpath
build      : |
    %make
install    : |
    %make_install
