name       : sdl2
version    : 2.0.10
release    : 18
source     :
    - https://www.libsdl.org/release/SDL2-2.0.10.tar.gz : b4656c13a1f0d0023ae2f4a9cf08ec92fffb464e0f24238337784159b8b91d57
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : Simple DirectMedia Layer
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(ice)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xcursor)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xscrnsaver)
    - pkgconfig(wayland-protocols)
    - sndio-32bit-devel
patterns   :
    - devel : /usr/bin
setup      : |
    %configure --enable-shared \
               --enable-alsa \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath \
               --enable-video-wayland \
               --enable-video-x11 \
               --enable-sdl-dlopen \
               --disable-rpath
build      : |
    %make
install    : |
    %make_install
