name       : sdl2
version    : 2.28.3
release    : 39
source     :
    - https://www.libsdl.org/release/SDL2-2.28.3.tar.gz : 7acb8679652701a2504d734e2ba7543ec1a83e310498ddd22fd44bf965eb5518
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : Simple DirectMedia Layer
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gbm)
    - pkgconfig32(ice)
    - pkgconfig32(libdecor-0)
    - pkgconfig32(libpipewire-0.3)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(wayland-client)
    - pkgconfig32(xcursor)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xscrnsaver)
    - pkgconfig(wayland-protocols)
patterns   :
    - devel : /usr/bin
setup      : |
    %configure --enable-libdecor \
               --enable-shared \
               --enable-sse2 \
               --enable-ssemath \
               --enable-video-wayland \
               --enable-video-x11 \
               --disable-alsa-shared \
               --disable-kmsdrm-shared \
               --disable-libdecor-shared \
               --disable-libsamplerate-shared \
               --disable-pipewire-shared \
               --disable-pulseaudio-shared \
               --disable-rpath \
               --disable-static \
               --disable-wayland-shared \
               --disable-x11-shared
build      : |
    %make
install    : |
    %make_install
