name       : sdl2
version    : 2.0.14
release    : 23
source     :
    - https://www.libsdl.org/release/SDL2-2.0.14.tar.gz : d8215b571a581be1332d2106f8036fcb03d12a70bae01e20f424976d275432bc
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : Simple DirectMedia Layer
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(ice)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(wayland-client)
    - pkgconfig32(xcursor)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xscrnsaver)
    - pkgconfig(wayland-protocols)
    - sndio-32bit-devel
patterns   :
    - devel : /usr/bin
setup      : |
    %configure --enable-shared \
               --enable-alsa \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath \
               --enable-video-wayland \
               --enable-video-x11 \
               --enable-sdl-dlopen \
               --disable-rpath \
               --disable-static
build      : |
    %make
install    : |
    %make_install
