name       : sdl2
version    : 2.24.0
release    : 29
source     :
    - https://www.libsdl.org/release/SDL2-2.24.0.tar.gz : 91e4c34b1768f92d399b078e171448c6af18cafda743987ed2064a28954d6d97
license    : Zlib
component  : multimedia.library
emul32     : yes
optimize   : speed
summary    : Simple DirectMedia Layer
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gl)
    - pkgconfig32(ice)
    - pkgconfig32(libdecor-0)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(wayland-client)
    - pkgconfig32(xcursor)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xscrnsaver)
    - pkgconfig(wayland-protocols)
    - sndio-32bit-devel
rundeps    :
    - libdecor
    - 32bit :
        - libdecor-32bit
patterns   :
    - devel : /usr/bin
setup      : |
    %configure --enable-shared \
               --enable-alsa \
               --enable-libdecor \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath \
               --enable-video-wayland \
               --enable-video-x11 \
               --enable-sdl-dlopen \
               --disable-rpath \
               --disable-static
build      : |
    %make
install    : |
    %make_install
