name       : sdl2
version    : 2.0.5
release    : 5
source     :
    - https://www.libsdl.org/release/SDL2-2.0.5.tar.gz : 442038cf55965969f2ff06d976031813de643af9c9edc9e331bd761c242e8785
license    :
    - zlib
summary    : Simple DirectMedia Layer
builddeps  :
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig(wayland-client)
    - pkgconfig32(wayland-client)
    - pkgconfig(libpulse)
    - pkgconfig32(libpulse)
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(ice)
    - pkgconfig32(ice)
    - pkgconfig(xinerama)
    - pkgconfig32(xinerama)
    - pkgconfig(xcursor)
    - pkgconfig32(xcursor)
    - pkgconfig(xscrnsaver)
    - pkgconfig32(xscrnsaver)
    - pkgconfig(wayland-client)
    - pkgconfig32(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig32(wayland-protocols)
    - pkgconfig(xkbcommon)
    - pkgconfig32(xkbcommon)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
patterns   :
    - devel : /usr/bin
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
setup      : |
    %configure --prefix=/usr \
               --enable-shared \
               --with-x \
               --enable-alsa \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath \
               --enable-video-wayland \
               --enable-video-x11 \
               --enable-sdl-dlopen \
build      : |
    %make
install    : |
    %make_install
